### ISSUE TITLE
(FE) Deployment Strategy Selection

### ISSUE THREAD

**Issue by devleejb** [yorkie-team/codepair-poc#36]
**What would you like to be added**:
Considering the current options, the deployment method will be selected. The following option is under consideration:
- GitHub Page

**Why is this needed**:
For users who want to use CodePair

**Additional Information**:

**Comment by devleejb** [comment]
Use this GitHub Actions YAML to deploy with GitHub Page.
Refer CodePair `.github/workflows/ghpages-publish.yml`

```YAML
name: GitHub Page Publish
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node 🔧
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install and Build 🔧 
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run: |
          npm install -f
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: dist
```
